#!/bin/bash

RED='\e[31m'
GREEN='\e[32m'
RESET='\e[0m'

declare -i step=1
declare -i hit=0
declare -a last_numbers=()

while true; do
    random_number=${RANDOM: -1}

    echo -e "Step: $step"
    echo -n "Please enter number from 0 to 9 (q - quit): "

    read input

    case "$input" in
        [0-9])
            if [[ "$input" == "$random_number" ]]; 
                then
                    echo -e "${GREEN}Hit! My number: $random_number${RESET}"
                    hit=$((hit + 1))
                    last_numbers+=("${GREEN}$random_number${RESET}")
                else
                    echo -e "${RED}Miss! My number: $random_number${RESET}"
                    last_numbers+=("${RED}$random_number${RESET}")
            fi

            total=$((step))
            hit_percent=$((hit * 100 / total))
            miss_percent=$((100 - hit_percent))

            if [[ ${#last_numbers[@]} -gt 10 ]]; 
                then
                    last_numbers=("${last_numbers[@]: -10}")
            fi

            echo "Hit: ${hit_percent}% Miss: ${miss_percent}%"
            echo -n "Numbers: "
            for num in "${last_numbers[@]}"; 
                do
                    echo -n -e "$num "
            done
            echo
            ;;
        q)
            exit 0
            ;;
        *)
            echo -e "${RED}Input error!${RESET}"
            continue
            ;;
    esac

    step=$((step + 1))
done
