#!/usr/bin/python3

import socket
import sys
from datetime import datetime

def start_server(port):
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_socket.bind(('0.0.0.0', port))
    server_socket.listen(5)
    
    while True:
        client_socket, addr = server_socket.accept()
        print(f"Подключение от {addr}")
        current_time = datetime.now().strftime("%d.%m.%Y %H:%M")
        client_socket.send(current_time.encode('utf-8'))
        client_socket.close()
        print(f"Соединение с {addr} закрыто")


if len(sys.argv) != 2:
    print("Укажите порт")
    sys.exit(1)
port = int(sys.argv[1])
start_server(port)
