#!/usr/bin/python3

import socket
import sys

def connect_to_server(ip, port):
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client_socket.connect((ip, port))
    data = client_socket.recv(1024).decode('utf-8')
    print(f"Текущая дата и время: {data}")
    client_socket.close()

if len(sys.argv) != 3:
    print("Укажите ip и порт")
    sys.exit(1)
ip = sys.argv[1]
port = int(sys.argv[2])
connect_to_server(ip, port)
